import { ITokenIssued, NewTokenIssued } from './token-issued.model';

export const sampleWithRequiredData: ITokenIssued = {
  id: 31275,
  uid: 23865,
};

export const sampleWithPartialData: ITokenIssued = {
  id: 27315,
  uid: 17282,
  phoneNumber: 'vice valiantly mortify',
  userEmail: 'pruner ha before',
  userLastName: 'bumpy',
  serviceName: 'kookily ick',
  serviceId: 30147,
  terminalName: 'sicken apropos yuck',
  terminalId: 22485,
  orgTerminalId: 2280,
  isQueue: true,
  isCancel: false,
  isRecall: true,
  isTimeout: true,
  assignedDay: 5120,
  assignedHour: 22424,
  assignedTimeZoneOffset: 885,
  assignedNow: 'under zowie swiftly',
  completedYear: 4731,
  completedMonth: 15887,
  completedMin: 982,
  completedTimeZoneOffset: 25120,
  completedNow: 'brr',
  createdYear: 16046,
  createdHour: 29725,
  createdTimeZoneOffset: 30546,
  createdTimeZoneName: 'selfishly',
  createdNow: 'weather garter however',
  createdDate: 3379,
  modifiedYear: 25029,
  modifiedMonth: 21533,
  modifiedMin: 30554,
  modifiedTimeZoneName: 'coaxingly colorfully',
  modifiedNow: 'suburban electrocute',
  modifiedDate: 6032,
  transferedMonth: 10670,
  transferedDate: 13645,
  transferedTimeZoneName: 'wearily',
  transferedNow: 'after',
  departmentName: 'lazily',
  orderId: 'yet',
  reset: true,
  resetDate: 16395,
  resetUid: 4291,
};

export const sampleWithFullData: ITokenIssued = {
  id: 25605,
  uid: 13492,
  profileBizId: 32284,
  phoneNumber: 'peg hole badly',
  phoneIsoCode: 'roughly',
  phoneCode: 'thoroughly after bitterly',
  userEmail: 'like',
  userFirstName: 'uh-huh despite',
  userLastName: 'cytokine parallel',
  tokenLetter: 'declutter bleakly spokeswoman',
  tokenNumber: 1786,
  serviceName: 'peacoat sedately bleakly',
  serviceId: 21361,
  terminalName: 'fooey spirituality picturesque',
  terminalId: 7146,
  orgTerminalName: 'around grow',
  orgTerminalId: 15493,
  statusName: 'yet',
  statusCode: 23506,
  isPending: true,
  isQueue: false,
  isReject: true,
  isAbsent: false,
  isCancel: false,
  isRecall: false,
  isCompleted: true,
  isTimeout: false,
  assignedDate: 26441,
  assignedYear: 26351,
  assignedMonth: 22141,
  assignedDay: 32452,
  assignedHour: 12180,
  assignedMin: 13183,
  assignedTimeZoneOffset: 4565,
  assignedTimeZoneName: 'the',
  assignedNow: 'cautiously',
  assignedUid: 1220,
  completedYear: 30798,
  completedMonth: 16133,
  completedDay: 27660,
  completedHour: 7224,
  completedMin: 7277,
  completedTimeZoneOffset: 22084,
  completedTimeZoneName: 'wet addle',
  completedNow: 'fondly shipwreck',
  completedDate: 16961,
  completedUid: 28022,
  createdYear: 32279,
  createdMonth: 32466,
  createdDay: 16840,
  createdHour: 21698,
  createdMin: 716,
  createdTimeZoneOffset: 8224,
  createdTimeZoneName: 'er agitated',
  createdNow: 'wimp austere',
  createdDate: 1309,
  modifiedYear: 7347,
  modifiedMonth: 32062,
  modifiedDay: 847,
  modifiedHour: 2785,
  modifiedMin: 9995,
  modifiedTimeZoneOffset: 8697,
  modifiedTimeZoneName: 'phooey cute yowza',
  modifiedNow: 'conduct unaccountably dividend',
  modifiedDate: 16750,
  transferedYear: 12219,
  transferedMonth: 26848,
  transferedDay: 482,
  transferedHour: 21896,
  transferedMin: 23566,
  transferedDate: 16698,
  transferedTimeZoneOffset: 17600,
  transferedTimeZoneName: 'needily',
  transferedNow: 'yahoo somber heavily',
  transferedUid: 3686,
  issuedFrom: 'ick noteworthy hm',
  departmentId: 3098,
  departmentName: 'atomise coordinator',
  bizName: 'who eurocentrism gentleman',
  rating: 22211.89,
  feedback: 'critical occupation',
  smsComingCount: 21598,
  pushComingCount: 29215,
  orderId: 'politely outside now',
  reset: false,
  resetDate: 8129,
  resetUid: 28255,
};

export const sampleWithNewData: NewTokenIssued = {
  uid: 15622,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
